services:
  db:
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  data: